name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.release.prerelease && 'testpypi' || 'pypi' }}
      url: ${{ github.event.release.prerelease && 'https://test.pypi.org/project/numbacs' || 'https://pypi.org/project/numbacs' }}

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Hatch
        run: pip install hatch

      - name: Build package with Hatch
        run: hatch build

      - name: Publish package to PyPi
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package to TestPyPi
        if: github.event.release.prerelease == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
